// Package ffmpegopts holds the single source of truth for FFmpeg option
// arity (whether an option takes a separate value argument).
//
// The table is generated by gen/main.go from `ffmpeg -h long` output and
// committed to the repository: no runtime probing, every consumer (CLI arg
// parser, worker executor, rewrite engine) queries this one map.
package ffmpegopts

import "strings"

//go:generate go run -tags gen ./gen

// booleanFlags maps an FFmpeg option name (no leading "-", no stream
// specifier) to true when the option does NOT take a separate value
// argument. Absent = value-taking. Entries below the GENERATED-START marker
// are produced by pkg/ffmpegopts/gen; the hand-written entries above it are
// corrections for options whose `ffmpeg -h long` description misrepresents
// their arity (each documents its evidence) — the generator skips any name
// already written here so regeneration cannot duplicate keys.
var booleanFlags = map[string]bool{
	// Help prints no placeholder, yet these consume the next argument
	// (verified against native ffmpeg n9: "-opt /dev/null" reports
	// "At least one output file must be specified", i.e. /dev/null was
	// swallowed as a value):
	"filter_threads":         false,
	"thread_queue_size":      false,
	"shortest_buf_duration":  false,
	"copypriorss":            false,
	"stats_enc_post":         false,
	"stats_enc_post_fmt":     false,
	"stats_enc_pre":          false,
	"stats_enc_pre_fmt":      false,
	"stats_mux_pre":          false,
	"stats_mux_pre_fmt":      false,
	"vstats_version":         false, // "Expected number for vstats_version but found: ..."
	"apply_cropping":         false,
	"content_light":          false,
	"guess_layout_max":       false,
	"mastering_display":      false,
	"seek_timestamp":         false,
	"filter_complex_threads": false, // "Expected number ... but found: /dev/null"
	"filter_buffered_frames": false, // same signal

	// Help prints no placeholder, yet ffmpeg requires a value:
	"fps_mode": false, // takes passthrough|cfr|vbr

	// Help prints an empty "<>" or a misleading placeholder, yet these
	// accept/require a value:
	"discard":              false, // none|default|nongeneric|all|bidir|nonkey|all_keyframe
	"disposition":          false, // disposition spec
	"frame_drop_threshold": false, // float
	"reinit_filter":        false, // 0/1 (per-stream)
	"drop_changed":         false, // 0/1
	"apad":                 false, // pad duration

	// Help prints a placeholder, yet these are plain switches:
	"re":           true, // "-re <>  read input at native frame rate..."
	"xerror":       true, // "-xerror <error>  exit on error"
	"noautorotate": true, // negated switch of boolean -autorotate
	"hide_banner":  true, // optional-value in help; plain switch in practice

	// GENERATED-START (entries below are managed by pkg/ffmpegopts/gen)
	// Code generated by gen/main.go from `ffmpeg -h long`; DO NOT EDIT.
	// Regenerate with `go generate ./pkg/ffmpegopts` (53 boolean options).
	"accurate_seek":              true,
	"an":                         true,
	"auto_conversion_filters":    true,
	"autorotate":                 true,
	"autoscale":                  true,
	"benchmark":                  true,
	"benchmark_all":              true,
	"bitexact":                   true,
	"bsfs":                       true,
	"buildconf":                  true,
	"codecs":                     true,
	"colors":                     true,
	"copy_unknown":               true,
	"copyinkf":                   true,
	"copyts":                     true,
	"debug_ts":                   true,
	"decoders":                   true,
	"demuxers":                   true,
	"devices":                    true,
	"display_hflip":              true,
	"display_vflip":              true,
	"dispositions":               true,
	"dn":                         true,
	"dump":                       true,
	"encoders":                   true,
	"filters":                    true,
	"find_stream_info":           true,
	"fix_sub_duration":           true,
	"fix_sub_duration_heartbeat": true,
	"force_fps":                  true,
	"formats":                    true,
	"hex":                        true,
	"hwaccels":                   true,
	"ignore_unknown":             true,
	"layouts":                    true,
	"license":                    true,
	"muxers":                     true,
	"n":                          true,
	"pix_fmts":                   true,
	"print_graphs":               true,
	"protocols":                  true,
	"recast_media":               true,
	"report":                     true,
	"sample_fmts":                true,
	"shortest":                   true,
	"sn":                         true,
	"start_at_zero":              true,
	"stats":                      true,
	"stdin":                      true,
	"version":                    true,
	"vn":                         true,
	"vstats":                     true,
	"y":                          true,
	// GENERATED-END
}

// IsBoolean reports whether the option does not take a separate value.
// The name may carry a leading "-" and a stream specifier suffix ("-c:v");
// both are stripped before lookup. An inline "=value" form never consumes
// the next argument. The ffmpeg "-no<flag>" negation form of a boolean
// flag is also boolean ("-nostats" → base "stats").
func IsBoolean(flag string) bool {
	name := strings.TrimPrefix(flag, "-")
	if strings.IndexByte(name, '=') != -1 {
		return true // inline value form carries its own value
	}
	if idx := strings.IndexByte(name, ':'); idx != -1 {
		name = name[:idx]
	}
	if booleanFlags[name] {
		return true
	}
	// "-no<flag>" negation of a known boolean flag is itself boolean.
	if rest, ok := strings.CutPrefix(name, "no"); ok && rest != "" && !strings.HasPrefix(rest, "no") {
		return booleanFlags[rest]
	}
	return false
}
